package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/Mininglamp-OSS/octo-daemon-cli/internal"
)

const pm2AppName = "octo-daemon"

// bootstrapPM2 registers the daemon as a pm2-managed service. It is idempotent:
// running it repeatedly installs pm2 only if missing, rewrites the ecosystem
// file, and restarts (not duplicates) the app via startOrRestart.
//
// The bootstrapper itself is short-lived — it hands the long-running foreground
// server (`octo-daemon start`, no --daemon) to pm2 and exits.
func bootstrapPM2() error {
	// Refuse if a daemon is already running outside pm2 (e.g. a manual
	// `octo-daemon start`). pm2's own managed instance is fine — startOrRestart
	// below restarts it cleanly.
	if internal.IsLocked() && !pm2HasApp(pm2AppName) {
		pid, _ := internal.ReadLockPID()
		return &internal.ExitError{Code: 2, Message: fmt.Sprintf("a daemon is already running (pid %d) outside pm2 — run `octo-daemon stop` first", pid)}
	}

	pm2, err := ensurePM2()
	if err != nil {
		return err
	}

	// pm2 manages the resolved Go binary directly (interpreter: none), not the
	// npm JS shim — so SIGTERM on restart reaches Go, no orphaned child. The
	// resolved path lives inside the platform sub-package and is stable across
	// `npm install @latest`, so upgrades take effect without rewriting it.
	goBin, err := os.Executable()
	if err != nil {
		return &internal.ExitError{Code: 2, Message: fmt.Sprintf("resolve executable: %v", err)}
	}
	if resolved, err := filepath.EvalSymlinks(goBin); err == nil {
		goBin = resolved
	}

	ecoPath, err := writeEcosystem(goBin, resolveConfigPath())
	if err != nil {
		return err
	}
	fmt.Printf("wrote pm2 ecosystem: %s\n", ecoPath)

	if err := runPM2(pm2, "startOrRestart", ecoPath); err != nil {
		return &internal.ExitError{Code: 1, Message: fmt.Sprintf("pm2 startOrRestart failed: %v", err)}
	}
	if err := runPM2(pm2, "save"); err != nil {
		return &internal.ExitError{Code: 1, Message: fmt.Sprintf("pm2 save failed: %v", err)}
	}

	fmt.Printf("octo-daemon is now managed by pm2 (app %q).\n", pm2AppName)
	fmt.Println("To start pm2 (and the daemon) on boot, run the command printed by:")
	fmt.Println("  pm2 startup")
	return nil
}

// ensurePM2 returns the pm2 executable path, installing it globally via npm if
// it is not already on PATH. Install failures surface a clear error instead of
// failing silently (global npm installs often need sudo / a writable prefix).
func ensurePM2() (string, error) {
	if path, err := exec.LookPath("pm2"); err == nil {
		return path, nil
	}

	if _, err := exec.LookPath("npm"); err != nil {
		return "", &internal.ExitError{Code: 2, Message: "pm2 not found and npm is unavailable — install Node.js (which provides npm), then `npm install -g pm2`"}
	}

	fmt.Println("pm2 not found — installing globally via `npm install -g pm2`...")
	cmd := exec.Command("npm", "install", "-g", "pm2")
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return "", &internal.ExitError{Code: 1, Message: fmt.Sprintf("`npm install -g pm2` failed (%v) — global installs may need sudo or a writable npm prefix; install pm2 manually and retry", err)}
	}

	path, err := exec.LookPath("pm2")
	if err != nil {
		return "", &internal.ExitError{Code: 1, Message: "pm2 installed but not found on PATH — ensure the npm global bin directory is on PATH, then retry"}
	}
	return path, nil
}

// resolveConfigPath returns the absolute config path the pm2-managed daemon
// should read: the value of --config when given, else the default. It is made
// absolute because pm2 launches the daemon from its own working directory, so a
// relative path would not resolve.
func resolveConfigPath() string {
	cfgPath := flagConfigFile
	if cfgPath == "" {
		cfgPath = internal.ConfigFilePath()
	}
	if abs, err := filepath.Abs(cfgPath); err == nil {
		cfgPath = abs
	}
	return cfgPath
}

// writeEcosystem renders ~/.octo-daemon/ecosystem.config.js. The launched
// command is the foreground server (`start --config <abs>`); it MUST NOT carry
// --daemon, or pm2 would re-run the bootstrapper on every restart (infinite
// recursion). args is emitted as a JSON array so paths containing spaces are
// passed as single argv entries instead of being word-split by pm2.
func writeEcosystem(goBin, cfgPath string) (string, error) {
	dir := internal.DataDir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", &internal.ExitError{Code: 2, Message: fmt.Sprintf("create data dir: %v", err)}
	}
	ecoPath := filepath.Join(dir, "ecosystem.config.js")

	argv := []string{"start", "--config", cfgPath}
	content := fmt.Sprintf(`// Generated by `+"`octo-daemon start --daemon`"+`. Do not edit by hand.
module.exports = {
  apps: [{
    name: %s,
    script: %s,
    interpreter: "none",
    args: %s,
    autorestart: true,
    max_restarts: 10,
    restart_delay: 2000,
    kill_timeout: 5000,
  }]
};
`, jsValue(pm2AppName), jsValue(goBin), jsValue(argv))

	if err := os.WriteFile(ecoPath, []byte(content), 0o644); err != nil {
		return "", &internal.ExitError{Code: 2, Message: fmt.Sprintf("write ecosystem file: %v", err)}
	}
	return ecoPath, nil
}

// pm2HasApp reports whether pm2 already manages an app with the given name.
// `pm2 id <name>` prints a JSON array of process ids ("[]" when absent).
func pm2HasApp(name string) bool {
	pm2, err := exec.LookPath("pm2")
	if err != nil {
		return false
	}
	out, err := exec.Command(pm2, "id", name).Output()
	if err != nil {
		return false
	}
	var ids []int
	if err := json.Unmarshal([]byte(strings.TrimSpace(string(out))), &ids); err != nil {
		return false
	}
	return len(ids) > 0
}

// runPM2 runs a pm2 subcommand with its output streamed to the user.
func runPM2(pm2 string, args ...string) error {
	cmd := exec.Command(pm2, args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// jsValue encodes a Go value as a JS/JSON literal for embedding in
// ecosystem.config.js — strings become double-quoted literals (paths escaped
// safely) and a []string becomes a JSON array of argv entries.
func jsValue(v any) string {
	b, _ := json.Marshal(v)
	return string(b)
}
